INSERT INTO public.tbl_employee
(employee_id, employee_name, employee_manager_id)
VALUES(1, 'Mary', NULL);
INSERT INTO public.tbl_employee
(employee_id, employee_name, employee_manager_id)
VALUES(2, 'Fred', 1);
INSERT INTO public.tbl_employee
(employee_id, employee_name, employee_manager_id)
VALUES(3, 'Mary', 2);
INSERT INTO public.tbl_employee
(employee_id, employee_name, employee_manager_id)
VALUES(4, 'Vio', 3);
INSERT INTO public.tbl_employee
(employee_id, employee_name, employee_manager_id)
VALUES(5, 'Mora', 2);
INSERT INTO public.tbl_employee
(employee_id, employee_name, employee_manager_id)
VALUES(6, 'Bill', 5);
INSERT INTO public.tbl_employee
(employee_id, employee_name, employee_manager_id)
VALUES(7, 'John', 6);
INSERT INTO public.tbl_employee
(employee_id, employee_name, employee_manager_id)
VALUES(8, 'George', 1);
INSERT INTO public.tbl_employee
(employee_id, employee_name, employee_manager_id)
VALUES(9, 'Chilla', 8);
INSERT INTO public.tbl_employee
(employee_id, employee_name, employee_manager_id)
VALUES(10, 'Moya', 8);
INSERT INTO public.tbl_employee
(employee_id, employee_name, employee_manager_id)
VALUES(11, 'Silvy', 1);
INSERT INTO public.tbl_employee
(employee_id, employee_name, employee_manager_id)
VALUES(12, 'Hans', 11);
INSERT INTO public.tbl_employee
(employee_id, employee_name, employee_manager_id)
VALUES(13, 'Michael', 11);
INSERT INTO public.tbl_employee
(employee_id, employee_name, employee_manager_id)
VALUES(14, 'Richard', 11);
