### GET request with a header
GET http://localhost:8000/auth/csrf-token

### POST LOGIN
POST http://localhost:8000/auth/login
Content-Type: application/json
X-CSRF-TOKEN: CF0PE6Ty5pUbpFJvNtkEWEDO6wDEwCPIwcdzcaxPBf9PJQXHbmQ8IZ3A36Y2lWBcAfQwbyOtxjmm-Efl9KNLRM1_Mpx4QGOk

{
  "username": "Mary",
  "password": "12345"
}


