### GET request with a header
GET http://localhost:8000/auth/csrf-token

### POST LOGIN
POST http://localhost:8000/auth/login
Content-Type: application/json
X-CSRF-TOKEN: RPIMtvAngbs53o8gHZdiUIMMej5UWGvFRpuS66CZWlF1Y7rrcMM1hpIXt9oUuOwUJLpWZrM9V19nPQ_odan305msPGFNVdvd

{
  "username": "Mary",
  "password": "12345"
}


